import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Roda em Node.js — não usar código client-side aqui.

/**
 * Trilhas conforme ADR-0001 e a decisão de produto:
 * - `produtoSidebar`     — requisitos, regras de negócio, casos de uso (PO + DEV)
 * - `apiSidebar`         — referência de API (integradores)
 * - `arquiteturaSidebar` — decisões estruturais e padrões (quem implementa/opera);
 *                          indexa ADRs sem duplicar autoridade (ADR-0002).
 */
const sidebars: SidebarsConfig = {
  produtoSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Produto e domínio',
      collapsed: false,
      items: [
        'produto/visao',
        'produto/dominio/index',
        'produto/taxonomia-rastreabilidade-requisitos',
        'produto/requisitos/index',
        'produto/regras-negocio/index',
        'produto/regras-negocio/conceitos',
        'produto/rastreabilidade/index',
        'produto/mvp-selecao/index',
        'produto/casos-de-uso/index',
        'produto/conformidade-legal/index',
        'produto/checklist-publicacao/index',
        {
          type: 'category',
          label: 'Modelo de negócio',
          items: [
            'produto/modelo-negocio/selecao',
            'produto/modelo-negocio/configurar-publicar',
            'produto/modelo-negocio/coleta-fatos-derivacao',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Convenções',
      collapsed: false,
      items: ['personas/cadastros'],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'Referência de API',
      collapsed: false,
      items: ['referencia-api/proof-gate'],
    },
    {
      type: 'category',
      label: 'Catálogo de erros',
      collapsed: false,
      // O `link` de doc é o que faz `useCurrentSidebarCategory()` resolver esta
      // categoria na página de visão geral, que lista as entradas a partir dela.
      link: {type: 'doc', id: 'erros/index'},
      items: [
        'erros/uniplus.selecao.processo_seletivo.localidade_ausente',
        'erros/uniplus.selecao.processo_seletivo.fuso_institucional_nao_reconhecido',
        'erros/uniplus.selecao.processo_seletivo.algoritmo_contagem_prazo_nao_declarado',
        'erros/uniplus.selecao.processo_seletivo.calendario_vigente_ausente',
        'erros/uniplus.selecao.regra_recurso_fase.prazo_em_dias_corridos',
        'erros/uniplus.selecao.regra_recurso_fase.prazo_em_fracao_de_dia_util',
        'erros/uniplus.cidade_referencia.codigo_ibge_obrigatorio',
        'erros/uniplus.cidade_referencia.codigo_ibge_formato_invalido',
        'erros/uniplus.cidade_referencia.uf_obrigatoria',
        'erros/uniplus.cidade_referencia.uf_incoerente',
        'erros/uniplus.cidade_referencia.nome_obrigatorio',
        'erros/uniplus.cidade_referencia.nome_caractere_nulo',
        'erros/uniplus.cidade_referencia.nome_tamanho',
        'erros/uniplus.cpf.vazio',
        'erros/uniplus.cpf.invalido',
        'erros/uniplus.email.vazio',
        'erros/uniplus.email.invalido',
        'erros/uniplus.nome_social.nome_civil_vazio',
        'erros/uniplus.nota_final.negativa',
        'erros/uniplus.cursor.invalido',
        'erros/uniplus.cursor.expirado',
        'erros/uniplus.cursor.limit_invalido',
        'erros/uniplus.cursor.direcao_invalida',
        'erros/uniplus.idempotency.key_ausente',
        'erros/uniplus.idempotency.key_malformada',
        'erros/uniplus.publicacoes.tipo_ato.codigo_obrigatorio',
        'erros/uniplus.publicacoes.tipo_ato.codigo_tamanho',
        'erros/uniplus.publicacoes.tipo_ato.codigo_formato',
        'erros/uniplus.publicacoes.tipo_ato.codigo_imutavel',
        'erros/uniplus.publicacoes.tipo_ato.nome_obrigatorio',
        'erros/uniplus.publicacoes.tipo_ato.nome_tamanho',
        'erros/uniplus.publicacoes.tipo_ato.base_legal_tamanho',
        'erros/uniplus.publicacoes.tipo_ato.vigencia_fim_anterior_ao_inicio',
        'erros/uniplus.publicacoes.tipo_ato.vigencia_sobreposta',
        'erros/uniplus.publicacoes.tipo_ato.nao_encontrado',
        'erros/uniplus.publicacoes.tipo_ato.id_divergente',
        'erros/uniplus.publicacoes.ato_normativo.tipo_sem_versao_vigente',
        'erros/uniplus.publicacoes.ato_normativo.versao_invocada_incompleta',
        'erros/uniplus.publicacoes.ato_normativo.ato_retificado_nao_encontrado',
        'erros/uniplus.publicacoes.ato_normativo.classe_congelamento_divergente',
        'erros/uniplus.publicacoes.ato_normativo.raiz_ja_retificada',
        'erros/uniplus.publicacoes.ato_normativo.objeto_ja_tem_ato_vivo_do_tipo',
        'erros/uniplus.idempotency.body_mismatch',
        'erros/uniplus.idempotency.processing_conflict',
        'erros/uniplus.idempotency.principal_requerido',
        'erros/uniplus.idempotency.body_muito_grande',
        'erros/uniplus.organizacao.unidade.nome_obrigatorio',
        'erros/uniplus.organizacao.unidade.nome_tamanho',
        'erros/uniplus.organizacao.unidade.sigla_obrigatoria',
        'erros/uniplus.organizacao.unidade.sigla_tamanho',
        'erros/uniplus.organizacao.unidade.sigla_ja_existe',
        'erros/uniplus.organizacao.unidade.codigo_obrigatorio',
        'erros/uniplus.organizacao.unidade.codigo_tamanho',
        'erros/uniplus.organizacao.unidade.codigo_ja_existe',
        'erros/uniplus.organizacao.unidade.slug_obrigatorio',
        'erros/uniplus.organizacao.unidade.slug_tamanho',
        'erros/uniplus.organizacao.unidade.slug_formato_invalido',
        'erros/uniplus.organizacao.unidade.slug_ja_existe',
        'erros/uniplus.organizacao.unidade.alias_tamanho',
        'erros/uniplus.organizacao.unidade.tipo_invalido',
        'erros/uniplus.organizacao.unidade.vigencia_fim_anterior_ao_inicio',
        'erros/uniplus.organizacao.unidade.superior_nao_encontrado',
        'erros/uniplus.organizacao.unidade.superior_forma_ciclo',
        'erros/uniplus.organizacao.unidade.nao_encontrada',
        'erros/uniplus.organizacao.unidade.remocao_bloqueada_por_subordinadas',
        'erros/uniplus.organizacao.unidade.remocao_bloqueada_por_instituicao',
        'erros/uniplus.organizacao.instituicao.codigo_emec_obrigatorio',
        'erros/uniplus.organizacao.instituicao.codigo_emec_tamanho',
        'erros/uniplus.organizacao.instituicao.nome_obrigatorio',
        'erros/uniplus.organizacao.instituicao.nome_tamanho',
        'erros/uniplus.organizacao.instituicao.sigla_obrigatoria',
        'erros/uniplus.organizacao.instituicao.sigla_tamanho',
        'erros/uniplus.organizacao.instituicao.organizacao_academica_obrigatoria',
        'erros/uniplus.organizacao.instituicao.organizacao_academica_tamanho',
        'erros/uniplus.organizacao.instituicao.categoria_administrativa_obrigatoria',
        'erros/uniplus.organizacao.instituicao.categoria_administrativa_tamanho',
        'erros/uniplus.organizacao.instituicao.campo_opcional_tamanho',
        'erros/uniplus.organizacao.instituicao.ja_existe',
        'erros/uniplus.organizacao.instituicao.nao_encontrada',
        'erros/uniplus.organizacao.instituicao.unidade_raiz_nao_encontrada',
        'erros/uniplus.organizacao.instituicao.unidade_raiz_nao_eh_reitoria',
        'erros/uniplus.organizacao.endereco_referencia.cep_obrigatorio',
        'erros/uniplus.organizacao.endereco_referencia.cep_formato_invalido',
        'erros/uniplus.organizacao.endereco_referencia.logradouro_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.numero_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.complemento_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.bairro_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.distrito_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.nivel_resolucao_obrigatorio',
        'erros/uniplus.organizacao.endereco_referencia.nivel_resolucao_invalido',
        'erros/uniplus.organizacao.endereco_referencia.origem_obrigatoria',
        'erros/uniplus.organizacao.endereco_referencia.origem_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.latitude_fora_de_faixa',
        'erros/uniplus.organizacao.endereco_referencia.longitude_fora_de_faixa',
        'erros/uniplus.organizacao.endereco_referencia.cidade_incoerente',
        'erros/uniplus.organizacao.endereco_referencia.cidade_obrigatoria_com_endereco',
        'erros/uniplus.configuracao.calendario_dias_uteis.versao_dataset_obrigatoria',
        'erros/uniplus.configuracao.calendario_dias_uteis.versao_dataset_tamanho',
        'erros/uniplus.configuracao.calendario_dias_uteis.sem_dia_nao_util',
        'erros/uniplus.configuracao.calendario_dias_uteis.dia_nao_util_nulo',
        'erros/uniplus.configuracao.calendario_dias_uteis.abrangencia_invalida',
        'erros/uniplus.configuracao.calendario_dias_uteis.snapshot_municipal_apenas_para_municipal',
        'erros/uniplus.configuracao.calendario_dias_uteis.uf_obrigatoria_para_estadual',
        'erros/uniplus.configuracao.calendario_dias_uteis.uf_apenas_para_estadual',
        'erros/uniplus.configuracao.calendario_dias_uteis.uf_formato_invalido',
        'erros/uniplus.configuracao.calendario_dias_uteis.descricao_obrigatoria',
        'erros/uniplus.configuracao.calendario_dias_uteis.descricao_tamanho',
        'erros/uniplus.configuracao.calendario_dias_uteis.data_duplicada_no_dataset',
        'erros/uniplus.configuracao.calendario_dias_uteis.ja_vigente',
        'erros/uniplus.configuracao.calendario_dias_uteis.nao_remove_vigente',
        'erros/uniplus.configuracao.calendario_dias_uteis.nao_encontrado',
        'erros/uniplus.configuracao.calendario_dias_uteis.conflito_de_concorrencia',
        'erros/uniplus.configuracao.oferta_curso.curso_inexistente_ou_removido',
        'erros/uniplus.configuracao.oferta_curso.local_oferta_inexistente_ou_removido',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_inexistente',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_origem_obrigatoria',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_sigla_obrigatoria',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_sigla_tamanho',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_nome_obrigatorio',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_nome_tamanho',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_tipo_obrigatorio',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_tipo_tamanho',
        'erros/uniplus.configuracao.oferta_curso.programa_de_oferta_invalido',
        'erros/uniplus.configuracao.oferta_curso.formato_pedagogico_invalido',
        'erros/uniplus.configuracao.oferta_curso.turno_invalido',
        'erros/uniplus.configuracao.oferta_curso.base_legal_obrigatoria_para_programa_nao_regular',
        'erros/uniplus.configuracao.oferta_curso.vagas_anuais_negativas',
        'erros/uniplus.configuracao.oferta_curso.e_mec_codigo_tamanho',
        'erros/uniplus.configuracao.oferta_curso.codigo_sga_tamanho',
        'erros/uniplus.configuracao.oferta_curso.base_legal_tamanho',
        'erros/uniplus.configuracao.oferta_curso.ato_autorizacao_mec_tamanho',
        'erros/uniplus.configuracao.oferta_curso.nao_encontrada',
        'erros/uniplus.configuracao.modalidade.codigo_obrigatorio',
        'erros/uniplus.configuracao.modalidade.codigo_formato_invalido',
        'erros/uniplus.configuracao.modalidade.codigo_ja_existe',
        'erros/uniplus.configuracao.modalidade.descricao_tamanho',
        'erros/uniplus.configuracao.modalidade.natureza_invalida',
        'erros/uniplus.configuracao.modalidade.composicao_vagas_invalida',
        'erros/uniplus.configuracao.modalidade.regra_remanejamento_invalida',
        'erros/uniplus.configuracao.modalidade.natureza_remanejamento_incoerente',
        'erros/uniplus.configuracao.modalidade.origem_obrigatoria_para_retira_de',
        'erros/uniplus.configuracao.modalidade.origem_apenas_para_retira_de',
        'erros/uniplus.configuracao.modalidade.argumento_remanejamento_obrigatorio',
        'erros/uniplus.configuracao.modalidade.acao_indeferimento_invalida',
        'erros/uniplus.configuracao.modalidade.referencia_inexistente_ou_inativa',
        'erros/uniplus.configuracao.modalidade.remocao_bloqueada_por_referencia',
        'erros/uniplus.configuracao.modalidade.estrutura_protegida_nao_editavel',
        'erros/uniplus.configuracao.modalidade.remocao_bloqueada_codigo_protegido',
        'erros/uniplus.configuracao.modalidade.criacao_bloqueada_codigo_protegido',
        'erros/uniplus.configuracao.modalidade.base_legal_tamanho',
        'erros/uniplus.configuracao.modalidade.nao_encontrada',
        'erros/uniplus.configuracao.fase_canonica.codigo_obrigatorio',
        'erros/uniplus.configuracao.fase_canonica.codigo_formato_invalido',
        'erros/uniplus.configuracao.fase_canonica.codigo_fora_do_conjunto_canonico',
        'erros/uniplus.configuracao.fase_canonica.codigo_ja_existe',
        'erros/uniplus.configuracao.fase_canonica.nome_obrigatorio',
        'erros/uniplus.configuracao.fase_canonica.nome_tamanho',
        'erros/uniplus.configuracao.fase_canonica.descricao_tamanho',
        'erros/uniplus.configuracao.fase_canonica.dono_tipico_obrigatorio',
        'erros/uniplus.configuracao.fase_canonica.dono_tipico_invalido',
        'erros/uniplus.configuracao.fase_canonica.agrupa_etapas_apenas_avaliacao',
        'erros/uniplus.configuracao.fase_canonica.complementacao_apenas_fases_permitidas',
        'erros/uniplus.configuracao.fase_canonica.base_legal_tamanho',
        'erros/uniplus.configuracao.fase_canonica.origem_data_obrigatoria',
        'erros/uniplus.configuracao.fase_canonica.origem_data_invalida',
        'erros/uniplus.configuracao.fase_canonica.resultado_definitivo_sem_produzir_resultado',
        'erros/uniplus.configuracao.fase_canonica.nao_encontrada',
      ],
    },
  ],

  arquiteturaSidebar: [
    'arquitetura/visao',
    {
      type: 'category',
      label: 'Frontend Angular',
      collapsed: false,
      items: ['arquitetura/frontend/estilos-angular'],
    },
    {
      type: 'category',
      label: 'Persistência e eventos',
      collapsed: false,
      items: [
        'arquitetura/event-sourcing/index',
        'arquitetura/congelamento-snapshot/index',
      ],
    },
    {
      type: 'category',
      label: 'Decisões arquiteturais',
      collapsed: false,
      items: ['arquitetura/adrs/index'],
    },
  ],
};

export default sidebars;
