import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Roda em Node.js — não usar código client-side aqui.

/**
 * Trilhas conforme ADR-0001 e a decisão de produto:
 * - `produtoSidebar`     — requisitos, regras de negócio, casos de uso (PO + DEV)
 * - `apiSidebar`         — referência de API (integradores)
 * - `arquiteturaSidebar` — decisões estruturais e padrões (quem implementa/opera);
 *                          indexa ADRs sem duplicar autoridade (ADR-0002).
 */
const sidebars: SidebarsConfig = {
  produtoSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Produto e domínio',
      collapsed: false,
      items: [
        'produto/visao',
        'produto/dominio/index',
        'produto/taxonomia-rastreabilidade-requisitos',
        'produto/requisitos/index',
        'produto/regras-negocio/index',
        'produto/regras-negocio/conceitos',
        'produto/rastreabilidade/index',
        'produto/mvp-selecao/index',
        'produto/casos-de-uso/index',
        'produto/conformidade-legal/index',
        'produto/checklist-publicacao/index',
        {
          type: 'category',
          label: 'Modelo de negócio',
          items: [
            'produto/modelo-negocio/selecao',
            'produto/modelo-negocio/configurar-publicar',
            'produto/modelo-negocio/coleta-fatos-derivacao',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Convenções',
      collapsed: false,
      items: ['personas/cadastros'],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'Referência de API',
      collapsed: false,
      items: ['referencia-api/proof-gate'],
    },
    {
      type: 'category',
      label: 'Catálogo de erros',
      collapsed: false,
      // O `link` de doc é o que faz `useCurrentSidebarCategory()` resolver esta
      // categoria na página de visão geral, que lista as entradas a partir dela.
      link: {type: 'doc', id: 'erros/index'},
      items: [
        'erros/uniplus.selecao.processo_seletivo.localidade_ausente',
        'erros/uniplus.selecao.processo_seletivo.fuso_institucional_nao_reconhecido',
        'erros/uniplus.selecao.processo_seletivo.algoritmo_contagem_prazo_nao_declarado',
        'erros/uniplus.selecao.processo_seletivo.calendario_vigente_ausente',
        'erros/uniplus.selecao.regra_recurso_fase.prazo_em_dias_corridos',
        'erros/uniplus.selecao.regra_recurso_fase.prazo_em_fracao_de_dia_util',
        'erros/uniplus.selecao.processo_seletivo.transicao_invalida',
        'erros/uniplus.selecao.processo_seletivo.conformidade_insuficiente',
        'erros/uniplus.selecao.processo_seletivo.conformidade_legal_insuficiente',
        'erros/uniplus.selecao.processo_seletivo.mutacao_pos_publicacao_bloqueada',
        'erros/uniplus.selecao.processo_seletivo.objeto_ja_tem_ato_vivo_do_tipo',
        'erros/uniplus.selecao.processo_seletivo.ato_ja_retificado',
        'erros/uniplus.selecao.processo_seletivo.tipo_de_ato_sem_versao_vigente',
        'erros/uniplus.selecao.processo_seletivo.tipo_de_ato_nao_congela_configuracao',
        'erros/uniplus.selecao.processo_seletivo.motivo_retificacao_obrigatorio',
        'erros/uniplus.selecao.processo_seletivo.ordem_etapa_duplicada',
        'erros/uniplus.selecao.processo_seletivo.id_etapa_duplicado',
        'erros/uniplus.selecao.etapa_processo.nome_obrigatorio',
        'erros/uniplus.selecao.etapa_processo.nome_tamanho',
        'erros/uniplus.selecao.etapa_processo.carater_obrigatorio',
        'erros/uniplus.selecao.etapa_processo.peso_invalido',
        'erros/uniplus.selecao.etapa_processo.nota_minima_invalida',
        'erros/uniplus.selecao.etapa_processo.ordem_invalida',
        'erros/uniplus.selecao.processo_seletivo.nenhuma_etapa_compoe_nota',
        'erros/uniplus.selecao.processo_seletivo.tipo_etapa_nao_encontrado_ou_inativo',
        'erros/uniplus.selecao.processo_seletivo.formulario_titulo_tamanho',
        'erros/uniplus.selecao.processo_seletivo.formulario_termo_aceite_texto_tamanho',
        'erros/uniplus.selecao.processo_seletivo.distribuicao_vagas_vazia',
        'erros/uniplus.selecao.processo_seletivo.oferta_curso_duplicada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.vo_base_invalido',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.pr_fora_do_limite',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.modalidades_vazias',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.modalidade_duplicada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.oferta_curso_nao_encontrada',
        'erros/uniplus.selecao.modalidade_selecionada.composicao_origem_obrigatoria',
        'erros/uniplus.selecao.modalidade_selecionada.composicao_origem_indevida',
        'erros/uniplus.selecao.modalidade_selecionada.cota_reservada_exige_cascata',
        'erros/uniplus.selecao.modalidade_selecionada.remanejamento_destino_obrigatorio',
        'erros/uniplus.selecao.modalidade_selecionada.remanejamento_cruzado_incompleto',
        'erros/uniplus.selecao.modalidade_selecionada.remanejamento_destino_indevido',
        'erros/uniplus.selecao.modalidade_selecionada.remanejamento_cruzado_indevido',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.composicao_origem_nao_selecionada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.remanejamento_destino_nao_selecionado',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.remanejamento_par_nao_selecionado',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.remanejamento_fallback_nao_selecionado',
        'erros/uniplus.selecao.modalidade_selecionada.codigo_obrigatorio',
        'erros/uniplus.selecao.modalidade_selecionada.natureza_legal_obrigatoria',
        'erros/uniplus.selecao.modalidade_selecionada.composicao_vagas_obrigatoria',
        'erros/uniplus.selecao.modalidade_selecionada.base_legal_obrigatoria',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.regra_distribuicao_nao_encontrada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.regra_distribuicao_tipo_invalido',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.referencia_demografica_nao_encontrada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.modalidade_nao_encontrada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.referencia_demografica_obrigatoria',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.modalidades_federais_incompletas',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.referencia_demografica_indevida',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.regra_ajuste_obrigatoria',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.retirada_federal_deve_ser_de_ampla_concorrencia',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quadro_modalidade_ausente',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quantidade_calculada_nao_informavel',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quantidade_declarada_obrigatoria',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quadro_ampla_concorrencia_negativa',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quantidade_vaga_negativa',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quadro_chave_colide',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.quadro_modalidade_nao_selecionada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.regra_ajuste_nao_encontrada',
        'erros/uniplus.selecao.configuracao_distribuicao_vagas.regra_ajuste_tipo_invalido',
        'erros/uniplus.selecao.vaga_ofertada.modalidade_codigo_obrigatorio',
        'erros/uniplus.selecao.criterio_desempate.ordem_invalida',
        'erros/uniplus.selecao.criterio_desempate.args_incompativeis_com_regra',
        'erros/uniplus.selecao.criterio_desempate.idade_minima_invalida',
        'erros/uniplus.selecao.criterio_desempate.regra_nao_encontrada',
        'erros/uniplus.selecao.criterio_desempate.regra_tipo_invalido',
        'erros/uniplus.selecao.criterio_desempate.etapa_ref_obrigatorio',
        'erros/uniplus.selecao.criterio_desempate.idade_minima_obrigatoria',
        'erros/uniplus.selecao.criterio_desempate.predicado_fato_incompleto',
        'erros/uniplus.selecao.regra_eliminacao.args_incompativeis_com_regra',
        'erros/uniplus.selecao.regra_eliminacao.nota_minima_invalida',
        'erros/uniplus.selecao.regra_eliminacao.minimo_invalido',
        'erros/uniplus.selecao.regra_eliminacao.regra_nao_encontrada',
        'erros/uniplus.selecao.regra_eliminacao.regra_tipo_invalido',
        'erros/uniplus.selecao.regra_eliminacao.etapa_ref_e_nota_minima_obrigatorios',
        'erros/uniplus.selecao.regra_eliminacao.minimo_obrigatorio',
        'erros/uniplus.selecao.configuracao_classificacao.n_opcoes_invalido',
        'erros/uniplus.selecao.configuracao_classificacao.arredondamento_indevido',
        'erros/uniplus.selecao.configuracao_classificacao.casas_arredondamento_indevido',
        'erros/uniplus.selecao.configuracao_classificacao.eliminacao_indevida',
        'erros/uniplus.selecao.configuracao_classificacao.arredondamento_obrigatorio',
        'erros/uniplus.selecao.configuracao_classificacao.casas_arredondamento_obrigatorio',
        'erros/uniplus.selecao.configuracao_classificacao.regra_nao_encontrada',
        'erros/uniplus.selecao.configuracao_classificacao.regra_tipo_invalido',
        'erros/uniplus.selecao.configuracao_classificacao.regra_arredondamento_versao_obrigatoria',
        'erros/uniplus.selecao.processo_seletivo.eliminacao_enem_fora_de_processo_enem',
        'erros/uniplus.cidade_referencia.codigo_ibge_obrigatorio',
        'erros/uniplus.cidade_referencia.codigo_ibge_formato_invalido',
        'erros/uniplus.cidade_referencia.uf_obrigatoria',
        'erros/uniplus.cidade_referencia.uf_incoerente',
        'erros/uniplus.cidade_referencia.nome_obrigatorio',
        'erros/uniplus.cidade_referencia.nome_caractere_nulo',
        'erros/uniplus.cidade_referencia.nome_tamanho',
        'erros/uniplus.cpf.vazio',
        'erros/uniplus.cpf.invalido',
        'erros/uniplus.email.vazio',
        'erros/uniplus.email.invalido',
        'erros/uniplus.nome_social.nome_civil_vazio',
        'erros/uniplus.nota_final.negativa',
        'erros/uniplus.cursor.invalido',
        'erros/uniplus.cursor.expirado',
        'erros/uniplus.cursor.limit_invalido',
        'erros/uniplus.cursor.direcao_invalida',
        'erros/uniplus.idempotency.key_ausente',
        'erros/uniplus.idempotency.key_malformada',
        'erros/uniplus.publicacoes.tipo_ato.codigo_obrigatorio',
        'erros/uniplus.publicacoes.tipo_ato.codigo_tamanho',
        'erros/uniplus.publicacoes.tipo_ato.codigo_formato',
        'erros/uniplus.publicacoes.tipo_ato.codigo_imutavel',
        'erros/uniplus.publicacoes.tipo_ato.nome_obrigatorio',
        'erros/uniplus.publicacoes.tipo_ato.nome_tamanho',
        'erros/uniplus.publicacoes.tipo_ato.base_legal_tamanho',
        'erros/uniplus.publicacoes.tipo_ato.vigencia_fim_anterior_ao_inicio',
        'erros/uniplus.publicacoes.tipo_ato.vigencia_sobreposta',
        'erros/uniplus.publicacoes.tipo_ato.nao_encontrado',
        'erros/uniplus.publicacoes.tipo_ato.id_divergente',
        'erros/uniplus.publicacoes.ato_normativo.tipo_sem_versao_vigente',
        'erros/uniplus.publicacoes.ato_normativo.versao_invocada_incompleta',
        'erros/uniplus.publicacoes.ato_normativo.ato_retificado_nao_encontrado',
        'erros/uniplus.publicacoes.ato_normativo.classe_congelamento_divergente',
        'erros/uniplus.publicacoes.ato_normativo.raiz_ja_retificada',
        'erros/uniplus.publicacoes.ato_normativo.objeto_ja_tem_ato_vivo_do_tipo',
        'erros/uniplus.idempotency.body_mismatch',
        'erros/uniplus.idempotency.processing_conflict',
        'erros/uniplus.idempotency.principal_requerido',
        'erros/uniplus.idempotency.body_muito_grande',
        'erros/uniplus.organizacao.unidade.nome_obrigatorio',
        'erros/uniplus.organizacao.unidade.nome_tamanho',
        'erros/uniplus.organizacao.unidade.sigla_obrigatoria',
        'erros/uniplus.organizacao.unidade.sigla_tamanho',
        'erros/uniplus.organizacao.unidade.sigla_ja_existe',
        'erros/uniplus.organizacao.unidade.codigo_obrigatorio',
        'erros/uniplus.organizacao.unidade.codigo_tamanho',
        'erros/uniplus.organizacao.unidade.codigo_ja_existe',
        'erros/uniplus.organizacao.unidade.slug_obrigatorio',
        'erros/uniplus.organizacao.unidade.slug_tamanho',
        'erros/uniplus.organizacao.unidade.slug_formato_invalido',
        'erros/uniplus.organizacao.unidade.slug_ja_existe',
        'erros/uniplus.organizacao.unidade.alias_tamanho',
        'erros/uniplus.organizacao.unidade.tipo_invalido',
        'erros/uniplus.organizacao.unidade.vigencia_fim_anterior_ao_inicio',
        'erros/uniplus.organizacao.unidade.superior_nao_encontrado',
        'erros/uniplus.organizacao.unidade.superior_forma_ciclo',
        'erros/uniplus.organizacao.unidade.nao_encontrada',
        'erros/uniplus.organizacao.unidade.remocao_bloqueada_por_subordinadas',
        'erros/uniplus.organizacao.unidade.remocao_bloqueada_por_instituicao',
        'erros/uniplus.organizacao.instituicao.codigo_emec_obrigatorio',
        'erros/uniplus.organizacao.instituicao.codigo_emec_tamanho',
        'erros/uniplus.organizacao.instituicao.nome_obrigatorio',
        'erros/uniplus.organizacao.instituicao.nome_tamanho',
        'erros/uniplus.organizacao.instituicao.sigla_obrigatoria',
        'erros/uniplus.organizacao.instituicao.sigla_tamanho',
        'erros/uniplus.organizacao.instituicao.organizacao_academica_obrigatoria',
        'erros/uniplus.organizacao.instituicao.organizacao_academica_tamanho',
        'erros/uniplus.organizacao.instituicao.categoria_administrativa_obrigatoria',
        'erros/uniplus.organizacao.instituicao.categoria_administrativa_tamanho',
        'erros/uniplus.organizacao.instituicao.campo_opcional_tamanho',
        'erros/uniplus.organizacao.instituicao.ja_existe',
        'erros/uniplus.organizacao.instituicao.nao_encontrada',
        'erros/uniplus.organizacao.instituicao.unidade_raiz_nao_encontrada',
        'erros/uniplus.organizacao.instituicao.unidade_raiz_nao_eh_reitoria',
        'erros/uniplus.organizacao.endereco_referencia.cep_obrigatorio',
        'erros/uniplus.organizacao.endereco_referencia.cep_formato_invalido',
        'erros/uniplus.organizacao.endereco_referencia.logradouro_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.numero_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.complemento_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.bairro_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.distrito_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.nivel_resolucao_obrigatorio',
        'erros/uniplus.organizacao.endereco_referencia.nivel_resolucao_invalido',
        'erros/uniplus.organizacao.endereco_referencia.origem_obrigatoria',
        'erros/uniplus.organizacao.endereco_referencia.origem_tamanho',
        'erros/uniplus.organizacao.endereco_referencia.latitude_fora_de_faixa',
        'erros/uniplus.organizacao.endereco_referencia.longitude_fora_de_faixa',
        'erros/uniplus.organizacao.endereco_referencia.cidade_incoerente',
        'erros/uniplus.organizacao.endereco_referencia.cidade_obrigatoria_com_endereco',
        'erros/uniplus.configuracao.calendario_dias_uteis.versao_dataset_obrigatoria',
        'erros/uniplus.configuracao.calendario_dias_uteis.versao_dataset_tamanho',
        'erros/uniplus.configuracao.calendario_dias_uteis.sem_dia_nao_util',
        'erros/uniplus.configuracao.calendario_dias_uteis.dia_nao_util_nulo',
        'erros/uniplus.configuracao.calendario_dias_uteis.abrangencia_invalida',
        'erros/uniplus.configuracao.calendario_dias_uteis.snapshot_municipal_apenas_para_municipal',
        'erros/uniplus.configuracao.calendario_dias_uteis.uf_obrigatoria_para_estadual',
        'erros/uniplus.configuracao.calendario_dias_uteis.uf_apenas_para_estadual',
        'erros/uniplus.configuracao.calendario_dias_uteis.uf_formato_invalido',
        'erros/uniplus.configuracao.calendario_dias_uteis.descricao_obrigatoria',
        'erros/uniplus.configuracao.calendario_dias_uteis.descricao_tamanho',
        'erros/uniplus.configuracao.calendario_dias_uteis.data_duplicada_no_dataset',
        'erros/uniplus.configuracao.calendario_dias_uteis.ja_vigente',
        'erros/uniplus.configuracao.calendario_dias_uteis.nao_remove_vigente',
        'erros/uniplus.configuracao.calendario_dias_uteis.nao_encontrado',
        'erros/uniplus.configuracao.calendario_dias_uteis.conflito_de_concorrencia',
        'erros/uniplus.configuracao.oferta_curso.curso_inexistente_ou_removido',
        'erros/uniplus.configuracao.oferta_curso.local_oferta_inexistente_ou_removido',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_inexistente',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_origem_obrigatoria',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_sigla_obrigatoria',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_sigla_tamanho',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_nome_obrigatorio',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_nome_tamanho',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_tipo_obrigatorio',
        'erros/uniplus.configuracao.oferta_curso.unidade_ofertante_tipo_tamanho',
        'erros/uniplus.configuracao.oferta_curso.programa_de_oferta_invalido',
        'erros/uniplus.configuracao.oferta_curso.formato_pedagogico_invalido',
        'erros/uniplus.configuracao.oferta_curso.turno_invalido',
        'erros/uniplus.configuracao.oferta_curso.base_legal_obrigatoria_para_programa_nao_regular',
        'erros/uniplus.configuracao.oferta_curso.vagas_anuais_negativas',
        'erros/uniplus.configuracao.oferta_curso.e_mec_codigo_tamanho',
        'erros/uniplus.configuracao.oferta_curso.codigo_sga_tamanho',
        'erros/uniplus.configuracao.oferta_curso.base_legal_tamanho',
        'erros/uniplus.configuracao.oferta_curso.ato_autorizacao_mec_tamanho',
        'erros/uniplus.configuracao.oferta_curso.nao_encontrada',
        'erros/uniplus.configuracao.modalidade.codigo_obrigatorio',
        'erros/uniplus.configuracao.modalidade.codigo_formato_invalido',
        'erros/uniplus.configuracao.modalidade.codigo_ja_existe',
        'erros/uniplus.configuracao.modalidade.descricao_tamanho',
        'erros/uniplus.configuracao.modalidade.natureza_invalida',
        'erros/uniplus.configuracao.modalidade.composicao_vagas_invalida',
        'erros/uniplus.configuracao.modalidade.regra_remanejamento_invalida',
        'erros/uniplus.configuracao.modalidade.natureza_remanejamento_incoerente',
        'erros/uniplus.configuracao.modalidade.origem_obrigatoria_para_retira_de',
        'erros/uniplus.configuracao.modalidade.origem_apenas_para_retira_de',
        'erros/uniplus.configuracao.modalidade.argumento_remanejamento_obrigatorio',
        'erros/uniplus.configuracao.modalidade.acao_indeferimento_invalida',
        'erros/uniplus.configuracao.modalidade.referencia_inexistente_ou_inativa',
        'erros/uniplus.configuracao.modalidade.remocao_bloqueada_por_referencia',
        'erros/uniplus.configuracao.modalidade.estrutura_protegida_nao_editavel',
        'erros/uniplus.configuracao.modalidade.remocao_bloqueada_codigo_protegido',
        'erros/uniplus.configuracao.modalidade.criacao_bloqueada_codigo_protegido',
        'erros/uniplus.configuracao.modalidade.base_legal_tamanho',
        'erros/uniplus.configuracao.modalidade.nao_encontrada',
        'erros/uniplus.configuracao.fase_canonica.codigo_obrigatorio',
        'erros/uniplus.configuracao.fase_canonica.codigo_formato_invalido',
        'erros/uniplus.configuracao.fase_canonica.codigo_fora_do_conjunto_canonico',
        'erros/uniplus.configuracao.fase_canonica.codigo_ja_existe',
        'erros/uniplus.configuracao.fase_canonica.nome_obrigatorio',
        'erros/uniplus.configuracao.fase_canonica.nome_tamanho',
        'erros/uniplus.configuracao.fase_canonica.descricao_tamanho',
        'erros/uniplus.configuracao.fase_canonica.dono_tipico_obrigatorio',
        'erros/uniplus.configuracao.fase_canonica.dono_tipico_invalido',
        'erros/uniplus.configuracao.fase_canonica.agrupa_etapas_apenas_avaliacao',
        'erros/uniplus.configuracao.fase_canonica.complementacao_apenas_fases_permitidas',
        'erros/uniplus.configuracao.fase_canonica.base_legal_tamanho',
        'erros/uniplus.configuracao.fase_canonica.origem_data_obrigatoria',
        'erros/uniplus.configuracao.fase_canonica.origem_data_invalida',
        'erros/uniplus.configuracao.fase_canonica.resultado_definitivo_sem_produzir_resultado',
        'erros/uniplus.configuracao.fase_canonica.nao_encontrada',
        'erros/uniplus.configuracao.tipo_processo.codigo_obrigatorio',
        'erros/uniplus.configuracao.tipo_processo.codigo_tamanho',
        'erros/uniplus.configuracao.tipo_processo.codigo_com_caractere_nulo',
        'erros/uniplus.configuracao.tipo_processo.codigo_reservado',
        'erros/uniplus.configuracao.tipo_processo.codigo_ja_existe',
        'erros/uniplus.configuracao.tipo_processo.nome_obrigatorio',
        'erros/uniplus.configuracao.tipo_processo.nome_tamanho',
        'erros/uniplus.configuracao.tipo_processo.nome_com_caractere_nulo',
        'erros/uniplus.configuracao.tipo_processo.descricao_tamanho',
        'erros/uniplus.configuracao.tipo_processo.descricao_com_caractere_nulo',
        'erros/uniplus.configuracao.tipo_processo.ja_desativado',
        'erros/uniplus.configuracao.tipo_processo.nao_encontrado',
        'erros/uniplus.configuracao.tipo_documento.codigo_obrigatorio',
        'erros/uniplus.configuracao.tipo_documento.codigo_tamanho',
        'erros/uniplus.configuracao.tipo_documento.codigo_ja_existe',
        'erros/uniplus.configuracao.tipo_documento.nome_obrigatorio',
        'erros/uniplus.configuracao.tipo_documento.nome_tamanho',
        'erros/uniplus.configuracao.tipo_documento.descricao_tamanho',
        'erros/uniplus.configuracao.tipo_documento.categoria_invalida',
        'erros/uniplus.configuracao.tipo_documento.formatos_aceitos_tamanho',
        'erros/uniplus.configuracao.tipo_documento.tamanho_maximo_invalido',
        'erros/uniplus.configuracao.tipo_documento.tipo_equivalente_tamanho',
        'erros/uniplus.configuracao.tipo_documento.tipo_equivalente_igual_codigo',
        'erros/uniplus.configuracao.tipo_documento.nao_encontrado',
        'erros/uniplus.configuracao.tipo_etapa.codigo_obrigatorio',
        'erros/uniplus.configuracao.tipo_etapa.codigo_tamanho',
        'erros/uniplus.configuracao.tipo_etapa.codigo_com_caractere_nulo',
        'erros/uniplus.configuracao.tipo_etapa.codigo_ja_existe',
        'erros/uniplus.configuracao.tipo_etapa.nome_obrigatorio',
        'erros/uniplus.configuracao.tipo_etapa.nome_tamanho',
        'erros/uniplus.configuracao.tipo_etapa.nome_com_caractere_nulo',
        'erros/uniplus.configuracao.tipo_etapa.descricao_tamanho',
        'erros/uniplus.configuracao.tipo_etapa.descricao_com_caractere_nulo',
        'erros/uniplus.configuracao.tipo_etapa.ja_desativado',
        'erros/uniplus.configuracao.tipo_etapa.nao_encontrado',
        'erros/uniplus.configuracao.tipo_banca.codigo_obrigatorio',
        'erros/uniplus.configuracao.tipo_banca.codigo_formato_invalido',
        'erros/uniplus.configuracao.tipo_banca.codigo_fora_do_conjunto_canonico',
        'erros/uniplus.configuracao.tipo_banca.codigo_ja_existe',
        'erros/uniplus.configuracao.tipo_banca.nome_obrigatorio',
        'erros/uniplus.configuracao.tipo_banca.nome_tamanho',
        'erros/uniplus.configuracao.tipo_banca.fase_tipica_tamanho',
        'erros/uniplus.configuracao.tipo_banca.descricao_tamanho',
        'erros/uniplus.configuracao.tipo_banca.nao_encontrado',
        'erros/uniplus.configuracao.tipo_deficiencia.nome_obrigatorio',
        'erros/uniplus.configuracao.tipo_deficiencia.nome_tamanho',
        'erros/uniplus.configuracao.tipo_deficiencia.nome_ja_existe',
        'erros/uniplus.configuracao.tipo_deficiencia.descricao_obrigatoria',
        'erros/uniplus.configuracao.tipo_deficiencia.descricao_tamanho',
        'erros/uniplus.configuracao.tipo_deficiencia.nao_encontrado',
        'erros/uniplus.configuracao.condicao_atendimento.codigo_obrigatorio',
        'erros/uniplus.configuracao.condicao_atendimento.codigo_formato_invalido',
        'erros/uniplus.configuracao.condicao_atendimento.codigo_ja_existe',
        'erros/uniplus.configuracao.condicao_atendimento.codigo_protegido_nao_editavel',
        'erros/uniplus.configuracao.condicao_atendimento.nome_obrigatorio',
        'erros/uniplus.configuracao.condicao_atendimento.nome_tamanho',
        'erros/uniplus.configuracao.condicao_atendimento.descricao_tamanho',
        'erros/uniplus.configuracao.condicao_atendimento.nao_encontrada',
        'erros/uniplus.configuracao.condicao_atendimento.remocao_bloqueada_codigo_protegido',
        'erros/uniplus.configuracao.recurso_acessibilidade.nome_obrigatorio',
        'erros/uniplus.configuracao.recurso_acessibilidade.nome_tamanho',
        'erros/uniplus.configuracao.recurso_acessibilidade.nome_ja_existe',
        'erros/uniplus.configuracao.recurso_acessibilidade.descricao_tamanho',
        'erros/uniplus.configuracao.recurso_acessibilidade.nao_encontrado',
        'erros/uniplus.configuracao.campus.sigla_obrigatoria',
        'erros/uniplus.configuracao.campus.sigla_tamanho',
        'erros/uniplus.configuracao.campus.sigla_ja_existe',
        'erros/uniplus.configuracao.campus.nome_obrigatorio',
        'erros/uniplus.configuracao.campus.nome_tamanho',
        'erros/uniplus.configuracao.campus.codigo_emec_tamanho',
        'erros/uniplus.configuracao.campus.nao_encontrado',
        'erros/uniplus.configuracao.campus.remocao_bloqueada_por_local_oferta',
        'erros/uniplus.configuracao.local_oferta.tipo_invalido',
        'erros/uniplus.configuracao.local_oferta.campus_responsavel_nao_encontrado',
        'erros/uniplus.configuracao.local_oferta.codigo_emec_tamanho',
        'erros/uniplus.configuracao.local_oferta.nao_encontrado',
        'erros/uniplus.configuracao.local_oferta.remocao_bloqueada_por_oferta_curso',
        'erros/uniplus.configuracao.curso.codigo_obrigatorio',
        'erros/uniplus.configuracao.curso.codigo_tamanho',
        'erros/uniplus.configuracao.curso.codigo_ja_existe',
        'erros/uniplus.configuracao.curso.nome_obrigatorio',
        'erros/uniplus.configuracao.curso.nome_tamanho',
        'erros/uniplus.configuracao.curso.grau_obrigatorio',
        'erros/uniplus.configuracao.curso.grau_tamanho',
        'erros/uniplus.configuracao.curso.nivel_ensino_obrigatorio',
        'erros/uniplus.configuracao.curso.nivel_ensino_tamanho',
        'erros/uniplus.configuracao.curso.grupo_area_enem_invalido',
        'erros/uniplus.configuracao.curso.nao_encontrado',
        'erros/uniplus.configuracao.curso.remocao_bloqueada_por_oferta_curso',
      ],
    },
    {
      type: 'category',
      label: 'Media types',
      collapsed: false,
      items: ['media-types/processo-seletivo/v1'],
    },
    {
      type: 'category',
      label: 'Changelog',
      collapsed: false,
      items: ['changelog/v1.0.0'],
    },
  ],

  arquiteturaSidebar: [
    'arquitetura/visao',
    {
      type: 'category',
      label: 'Frontend Angular',
      collapsed: false,
      items: ['arquitetura/frontend/estilos-angular'],
    },
    {
      type: 'category',
      label: 'Persistência e eventos',
      collapsed: false,
      items: [
        'arquitetura/event-sourcing/index',
        'arquitetura/congelamento-snapshot/index',
      ],
    },
    {
      type: 'category',
      label: 'Decisões arquiteturais',
      collapsed: false,
      items: ['arquitetura/adrs/index'],
    },
  ],
};

export default sidebars;
